select
    trip_id,
    pickup_datetime,
    dropoff_datetime,
    pickup_date as pickup_date_id,
    pickup_hour as pickup_time_id,
    vendor_id,
    rate_code_id,
    payment_type_id,
    pickup_location_id,
    dropoff_location_id,
    passenger_count,
    trip_distance,
    trip_duration_minutes,
    average_speed_mph,
    fare_amount,
    extra,
    mta_tax,
    tip_amount,
    tolls_amount,
    improvement_surcharge,
    congestion_surcharge,
    airport_fee,
    total_amount,
    source_file,
    source_url,
    ingestion_timestamp,
    batch_id
from {{ ref('stg_yellow_taxi_trips') }}
